# Generated by Django 5.2.5 on 2025-08-31 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studybuddy", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rooms",
            new_name="Room",
        ),
    ]
